# Author: Paul Côté
# Last Change Author: Paul Côté
# Last Date Changed: 2022/06/10

FROM golang:1.18.0-buster

RUN apt-get -y update \
  && apt-get -y upgrade \
  && apt-get -y install \
    git \
    build-essential \

RUN cd /tmp

RUN git clone https:/github.com/SSSOC-CAN/laniakea /tmp/laniakea \
  && cd /tmp/laniakea \
  && make install