FROM golang:1.18.0-buster

RUN apt-get -y update \
  && apt-get -y upgrade \
  && apt-get -y install \
    git \
    build-essential \

RUN cd /tmp

RUN git clone https:/github.com/SSSOC-CAN/fmtd /tmp/fmtd \
  && cd /tmp/fmtd \
  && git checkout build_tags \
  && make install tags="demo"